from dotenv import load_dotenv
load_dotenv()

"""
Django settings for realstate project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'fallback-nur-fuer-entwicklung')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pages.apps.PagesConfig',    # pages app
    'listings.apps.ListingsConfig',  # listings app
    'realtors.apps.RealtorsConfig',  # realtors app
    'django.contrib.humanize',     ## It will allow us to use human eyes( we can use comma etc by using this)
    'accounts.apps.AccountsConfig',  ## accounts app
    'contacts.apps.ContactsConfig',  ## contacts app
    'crispy_forms',
    'bootstrap4',
    'ckeditor',
    'ckeditor_uploader',
    'django_cleanup.apps.CleanupConfig',
    'main',
]

CKEDITOR_UPLOAD_PATH = 'uploads/'

# config ckeditor
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        # "height": 500,
        "height": 'auto',
        'width': 'auto',
        'toolbar_Custom': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo'],
            ['Link', 'Unlink', 'Anchor', 'Italic', 'Underline', ],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'],
            ['Source'],
        ],
    },
    'special': {
        'toolbar': 'Custom',
        'width': 'auto',
        'height': 'auto',
        # 'width': '75vh', 'height': '100%',
        'toolbar_Special': [
            ['Bold', 'CodeSnippet', 'Youtube'],
        ],
        'extraPlugins': ','.join(['codesnippet', 'youtube']),
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    
    # Custom Redirect Middleware
    'main.middleware.redirect_registry_middleware.RedirectRegistryMiddleware',
    'main.middleware.smart_redirect_middleware.SmartRedirectMiddleware',
]

ROOT_URLCONF = 'realstate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.set_language',
                'main.context_processors.get_my_translations',
                'main.context_processors.get_sitemap_translations',
                'main.context_processors.get_search_filter_translations',
            ],
        },
    },
]

WSGI_APPLICATION = 'realstate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# Database configuration
# Local dev: SQLite (default)
# Production: PostgreSQL via environment variables
if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/


# LANGUAGE_CODE = 'fi'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGE_CODE = 'ge'

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]
# Croatian English Polish Czech Russian Swedish Norway Slovak Dutch
LANGUAGES = [
    ('en', 'English'),
    ('ge', 'German'),
    ('fr', 'French'),
    ('gr', 'Greek'),
    ('hr', 'Croatian'),
    ('pl', 'Polish'),
    ('cz', 'Czech'),
    ('ru', 'Russian'),
    ('sw', 'Swedish'),
    ('no', 'Norway'),
    ('sk', 'Slovak'),
    ('nl', 'Dutch'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),           ## Haupt-Static-Ordner (CSS, Images, JS)
    os.path.join(BASE_DIR, 'realstate/static'), ## Zweiter Static-Ordner (webfonts für Font Awesome 5)
]
## after this apply on gitbash - python manage.py collectstatic, it will create the static folder in root directory


# Media Folder Settings
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

### Message Alerts (After submit reg/login etc form, it will show a message) Start ###
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger'  ## danger from Bootstrap
}
### Message Alerts (After submit reg/login etc form, it will show a message) End ###


CRISPY_TEMPLATE_PACK = 'uni_form'

## Email Config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.ethereal.email')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'


# === SICHERHEITS-EINSTELLUNGEN ===
# Schutz gegen Clickjacking
X_FRAME_OPTIONS = 'DENY'

# Schutz gegen XSS
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# CSRF Schutz
CSRF_COOKIE_SECURE = False  # True wenn HTTPS aktiv
CSRF_COOKIE_HTTPONLY = True

# Session-Sicherheit
SESSION_COOKIE_SECURE = False  # True wenn HTTPS aktiv
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 24 Stunden

# Passwort-Validierung
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 10}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# SICHERHEIT: Passwort-Reset Token nur 1 Stunde gueltig
PASSWORD_RESET_TIMEOUT = 3600
SESSION_COOKIE_AGE = 1209600
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 1209600
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 1209600
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
