# Generated by Django 4.2.1 on 2026-01-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='geprueft_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_status',
            field=models.CharField(choices=[('pruefung', 'Zur Pruefung'), ('aktiv', 'Aktiv (Online)'), ('verkauft', 'Verkauft'), ('pausiert', 'Pausiert'), ('abgelehnt', 'Abgelehnt')], default='pruefung', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='pruefung_fehler',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pruefung_notizen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
