# Generated by Django 4.2.1 on 2026-01-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_geprueft_am_listing_listing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_1_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Foto 2 Beschriftung'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_2_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Foto 3 Beschriftung'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_3_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Foto 4 Beschriftung'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_4_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Foto 5 Beschriftung'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_5_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Foto 6 Beschriftung'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_6_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Foto 7 Beschriftung'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_main_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hauptfoto Beschriftung'),
        ),
    ]
