# Generated by Django 4.2.1 on 2026-01-13 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "professional_type",
                    models.CharField(
                        choices=[
                            ("real_estate_agent", "Immobilienmakler"),
                            ("construction_company", "Bauunternehmen"),
                            ("lawyer", "Rechtsanwalt"),
                            ("tax_advisor", "Steuerberater"),
                            ("architect", "Architekt"),
                        ],
                        default="real_estate_agent",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Name / Firmenname"),
                ),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("email", models.EmailField(max_length=500)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("mobile", models.CharField(blank=True, max_length=50, null=True)),
                ("fax", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("istrien", "Istrien"),
                            ("kvarner", "Kvarner"),
                            ("dalmatien", "Dalmatien"),
                            ("zagreb", "Zagreb"),
                            ("slavonien", "Slavonien"),
                            ("andere", "Andere"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("country", models.CharField(default="Kroatien", max_length=100)),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Firmenname"
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="professionals/logos/"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="professionals/profiles/"
                    ),
                ),
                (
                    "portrait_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="professionals/portraits/"
                    ),
                ),
                (
                    "oib_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="OIB-Nummer"
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung (Original)"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung (Deutsch)"
                    ),
                ),
                (
                    "description_hr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung (Kroatisch)"
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Gesprochene Sprachen",
                    ),
                ),
                ("facebook", models.URLField(blank=True, max_length=500, null=True)),
                ("instagram", models.URLField(blank=True, max_length=500, null=True)),
                ("linkedin", models.URLField(blank=True, max_length=500, null=True)),
                ("twitter", models.URLField(blank=True, max_length=500, null=True)),
                ("youtube", models.URLField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=False, verbose_name="Aktiv")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verifiziert"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dienstleister",
                "verbose_name_plural": "Dienstleister",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("business_license", "Gewerbeschein"),
                            ("id_document", "Personalausweis/Reisepass"),
                            ("company_register", "Handelsregisterauszug"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="professionals/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="main.professional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumente",
            },
        ),
        migrations.CreateModel(
            name="ProfessionalContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("hr", "Hrvatski")], max_length=5
                    ),
                ),
                (
                    "about_text",
                    models.TextField(blank=True, null=True, verbose_name="Über uns"),
                ),
                (
                    "services_text",
                    models.TextField(blank=True, null=True, verbose_name="Leistungen"),
                ),
                (
                    "working_approach",
                    models.TextField(
                        blank=True, null=True, verbose_name="Arbeitsweise"
                    ),
                ),
                (
                    "faq_text",
                    models.TextField(blank=True, null=True, verbose_name="FAQ"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="main.professional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dienstleister-Inhalt",
                "verbose_name_plural": "Dienstleister-Inhalte",
                "unique_together": {("professional", "language")},
            },
        ),
    ]
