# Generated by Django 4.2.1 on 2026-01-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_add_professional_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="email_2fa_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="professional",
            name="email_2fa_code_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professional",
            name="email_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professional",
            name="must_setup_2fa",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="professional",
            name="totp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professional",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="professional",
            name="totp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
