# Generated by Django 4.2.1 on 2026-01-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_add_2fa_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="employee_count",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Mitarbeiterzahl"
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="founded_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Gründungsjahr"
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="show_contact_form",
            field=models.BooleanField(
                default=True, verbose_name="Kontaktformular anzeigen"
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="show_listings",
            field=models.BooleanField(default=True, verbose_name="Immobilien anzeigen"),
        ),
        migrations.AddField(
            model_name="professional",
            name="show_references",
            field=models.BooleanField(default=True, verbose_name="Referenzen anzeigen"),
        ),
        migrations.AddField(
            model_name="professional",
            name="show_social_media",
            field=models.BooleanField(
                default=True, verbose_name="Social Media anzeigen"
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="show_team",
            field=models.BooleanField(default=False, verbose_name="Team anzeigen"),
        ),
        migrations.AddField(
            model_name="professional",
            name="slogan",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Slogan/Motto"
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="specializations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Spezialisierungen"
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="tiktok",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="ReferenceProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Projekttitel"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Jahr"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Standort"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Projektart"
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True, null=True, upload_to="professionals/references/"
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="professionals/references/"
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True, null=True, upload_to="professionals/references/"
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True, null=True, upload_to="professionals/references/"
                    ),
                ),
                (
                    "image_5",
                    models.ImageField(
                        blank=True, null=True, upload_to="professionals/references/"
                    ),
                ),
                (
                    "image_6",
                    models.ImageField(
                        blank=True, null=True, upload_to="professionals/references/"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sortierreihenfolge"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Hervorgehoben"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_projects",
                        to="main.professional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referenzprojekt",
                "verbose_name_plural": "Referenzprojekte",
                "ordering": ["sort_order", "-year", "-created"],
            },
        ),
    ]
