# Generated by Django 4.2.1 on 2026-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_agent_facebook_agent_fax_agent_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='totp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
