# Generated by Django 4.2.1 on 2026-01-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_agent_totp_enabled_agent_totp_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='totp_enabled',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='totp_secret',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='totp_verified',
        ),
        migrations.AddField(
            model_name='agent',
            name='description_cz',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Czech)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description (German)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description (French)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_gr',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Greek)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_hr',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Croatian)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Dutch)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_no',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Norwegian)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Polish)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_sk',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Slovak)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Swedish)'),
        ),
    ]
