# Generated by Django 4.2.1 on 2025-01-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0011_agent_company_logo_agent_company_name_agent_domain_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="fax",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="instagram",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="mobile",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="youtube",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
