# Generated by Django 4.2.1 on 2026-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('page', models.CharField(max_length=50)),
                ('german', models.TextField(blank=True, null=True)),
                ('english', models.TextField(blank=True, null=True)),
                ('french', models.TextField(blank=True, null=True)),
                ('greek', models.TextField(blank=True, null=True)),
                ('croatian', models.TextField(blank=True, null=True)),
                ('polish', models.TextField(blank=True, null=True)),
                ('czech', models.TextField(blank=True, null=True)),
                ('russian', models.TextField(blank=True, null=True)),
                ('swedish', models.TextField(blank=True, null=True)),
                ('norwegian', models.TextField(blank=True, null=True)),
                ('slovak', models.TextField(blank=True, null=True)),
                ('dutch', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Statischer Inhalt',
                'verbose_name_plural': 'Statische Inhalte',
            },
        ),
    ]
