# Generated by Django 4.2.1 on 2026-01-08 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('professional_type', models.CharField(choices=[('real_estate_agent', 'Immobilienmakler'), ('construction_company', 'Bauunternehmen'), ('lawyer', 'Rechtsanwalt'), ('tax_advisor', 'Steuerberater'), ('architect', 'Architekt')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('istrien', 'Istrien'), ('kvarner', 'Kvarner'), ('dalmatien-nord', 'Nord-Dalmatien'), ('dalmatien-mitte', 'Mittel-Dalmatien'), ('dalmatien-sued', 'Süd-Dalmatien'), ('zagreb', 'Zagreb'), ('slavonien', 'Slavonien'), ('lika-gorski-kotar', 'Lika & Gorski Kotar')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('service_regions', models.CharField(blank=True, max_length=500, null=True)),
                ('languages_spoken', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='professionals/logos/')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='professionals/portraits/')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('oib_number', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional',
                'verbose_name_plural': 'Professionals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxAdvisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('professional_registration', models.CharField(blank=True, max_length=200, null=True)),
                ('core_services', models.CharField(blank=True, max_length=500, null=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='main.professional')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_info', models.CharField(blank=True, max_length=200, null=True)),
                ('property_focus', models.CharField(blank=True, max_length=300, null=True)),
                ('years_active', models.PositiveIntegerField(blank=True, null=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='main.professional')),
            ],
        ),
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_firm', models.CharField(blank=True, max_length=200, null=True)),
                ('bar_registration', models.CharField(blank=True, max_length=200, null=True)),
                ('practice_areas', models.CharField(blank=True, max_length=500, null=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to='main.professional')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_registration', models.CharField(blank=True, max_length=200, null=True)),
                ('project_types', models.CharField(blank=True, max_length=500, null=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='construction_profile', to='main.professional')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(blank=True, max_length=200, null=True)),
                ('chamber_registration', models.CharField(blank=True, max_length=200, null=True)),
                ('planning_focus', models.CharField(blank=True, max_length=500, null=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='architect_profile', to='main.professional')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('profile_summary', models.TextField(blank=True, null=True)),
                ('areas_of_activity', models.TextField(blank=True, null=True)),
                ('typical_situations', models.TextField(blank=True, null=True)),
                ('working_approach', models.TextField(blank=True, null=True)),
                ('faq_content', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('verification_statement', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='main.professional')),
            ],
            options={
                'verbose_name': 'Professional Content',
                'verbose_name_plural': 'Professional Contents',
                'unique_together': {('professional', 'language')},
            },
        ),
    ]
