# Generated by Django 4.2.1 on 2026-01-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_professional_taxadvisorprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registrierung', 'verbose_name_plural': 'Professionals'},
        ),
        migrations.AddField(
            model_name='professional',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='business_document',
            field=models.FileField(blank=True, help_text='Handelsregisterauszug, Kammerbescheinigung, etc.', null=True, upload_to='professionals/verification/business/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='id_document',
            field=models.FileField(blank=True, help_text='Personalausweis oder Reisepass (PDF/JPG)', null=True, upload_to='professionals/verification/id/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='profile_text_original',
            field=models.TextField(blank=True, help_text='Originaltext in der Eingabesprache', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='profile_text_style',
            field=models.CharField(blank=True, help_text='Stil des gewählten Profiltextes', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Interne Notizen zur Verifizierung', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Name des Mitarbeiters der verifiziert hat', max_length=100, null=True),
        ),
    ]
