# Generated by Django 4.2.1 on 2026-01-12 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_professional_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='has_portal_access',
            field=models.BooleanField(default=False, help_text='Zugang zum Makler-Portal'),
        ),
        migrations.AddField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
