# Generated by Django 4.2.1 on 2026-01-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_professional_has_portal_access_professional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='must_setup_2fa',
            field=models.BooleanField(default=True, help_text='Muss 2FA bei erstem Login einrichten'),
        ),
        migrations.AddField(
            model_name='professional',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professional',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='totp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
