# Generated by Django 4.2.1 on 2026-01-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_professional_must_setup_2fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='email_2fa_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='email_2fa_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='email_2fa_enabled',
            field=models.BooleanField(default=True, help_text='2FA per E-Mail aktiviert'),
        ),
    ]
