# Generated by Django 4.2.1 on 2026-01-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_professional_email_2fa_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='description_de',
            field=models.TextField(blank=True, help_text='Beschreibung Deutsch', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='description_en',
            field=models.TextField(blank=True, help_text='Beschreibung Englisch', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='description_hr',
            field=models.TextField(blank=True, help_text='Beschreibung Kroatisch', null=True),
        ),
    ]
