# Generated by Django 4.2.1 on 2026-01-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_professional_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='profile_views',
            field=models.PositiveIntegerField(default=0, help_text='Anzahl Profilaufrufe'),
        ),
    ]
