# Generated by Django 4.2.1 on 2026-01-15 13:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_professional_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='employee_count',
            field=models.CharField(blank=True, help_text='z.B. 1-5, 6-20, 21-50, 50+', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, help_text='Gruendungsjahr', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_contact_form',
            field=models.BooleanField(default=True, help_text='Kontaktformular anzeigen'),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_listings',
            field=models.BooleanField(default=True, help_text='Aktuelle Immobilien anzeigen'),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_references',
            field=models.BooleanField(default=True, help_text='Referenzprojekte anzeigen'),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_social_media',
            field=models.BooleanField(default=True, help_text='Social Media Links anzeigen'),
        ),
        migrations.AddField(
            model_name='professional',
            name='slogan',
            field=models.CharField(blank=True, help_text='Firmenslogan', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='specializations',
            field=models.TextField(blank=True, help_text='Spezialgebiete, kommagetrennt', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReferenceProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='professionals/references/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='professionals/references/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='professionals/references/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='professionals/references/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='professionals/references/')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='professionals/references/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_projects', to='main.professional')),
            ],
            options={
                'verbose_name': 'Referenzprojekt',
                'verbose_name_plural': 'Referenzprojekte',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
