# Generated by Django 4.2.1 on 2026-01-15 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_professional_employee_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architectprofile',
            options={'verbose_name': 'Architekt-Profil', 'verbose_name_plural': 'Architekt-Profile'},
        ),
        migrations.AlterModelOptions(
            name='constructioncompanyprofile',
            options={'verbose_name': 'Bauunternehmen-Profil', 'verbose_name_plural': 'Bauunternehmen-Profile'},
        ),
        migrations.AlterModelOptions(
            name='lawyerprofile',
            options={'verbose_name': 'Anwalt-Profil', 'verbose_name_plural': 'Anwalt-Profile'},
        ),
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['-created'], 'verbose_name': 'Dienstleister', 'verbose_name_plural': 'Dienstleister'},
        ),
        migrations.AlterModelOptions(
            name='professionalcontent',
            options={'verbose_name': 'Dienstleister-Inhalt', 'verbose_name_plural': 'Dienstleister-Inhalte'},
        ),
        migrations.AlterModelOptions(
            name='realestateagentprofile',
            options={'verbose_name': 'Makler-Profil', 'verbose_name_plural': 'Makler-Profile'},
        ),
        migrations.AlterModelOptions(
            name='referenceproject',
            options={'ordering': ['sort_order', '-year', '-created'], 'verbose_name': 'Referenzprojekt', 'verbose_name_plural': 'Referenzprojekte'},
        ),
        migrations.AlterModelOptions(
            name='taxadvisorprofile',
            options={'verbose_name': 'Steuerberater-Profil', 'verbose_name_plural': 'Steuerberater-Profile'},
        ),
        migrations.RenameField(
            model_name='architectprofile',
            old_name='chamber_registration',
            new_name='chamber_membership',
        ),
        migrations.RenameField(
            model_name='lawyerprofile',
            old_name='bar_registration',
            new_name='bar_association',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='logo',
            new_name='company_logo',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='portrait',
            new_name='portrait_photo',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='professionalcontent',
            old_name='generated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='realestateagentprofile',
            old_name='years_active',
            new_name='years_experience',
        ),
        migrations.RenameField(
            model_name='referenceproject',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='referenceproject',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='taxadvisorprofile',
            old_name='professional_registration',
            new_name='certification',
        ),
        migrations.RemoveField(
            model_name='architectprofile',
            name='office_name',
        ),
        migrations.RemoveField(
            model_name='architectprofile',
            name='planning_focus',
        ),
        migrations.RemoveField(
            model_name='constructioncompanyprofile',
            name='project_types',
        ),
        migrations.RemoveField(
            model_name='constructioncompanyprofile',
            name='trade_registration',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='law_firm',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='blocked_until',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='business_document',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='has_portal_access',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='profile_text_original',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='profile_text_style',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='profile_views',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='registration_ip',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='service_regions',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='verification_date',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='professionalcontent',
            name='areas_of_activity',
        ),
        migrations.RemoveField(
            model_name='professionalcontent',
            name='faq_content',
        ),
        migrations.RemoveField(
            model_name='professionalcontent',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='professionalcontent',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='professionalcontent',
            name='profile_summary',
        ),
        migrations.RemoveField(
            model_name='professionalcontent',
            name='typical_situations',
        ),
        migrations.RemoveField(
            model_name='professionalcontent',
            name='verification_statement',
        ),
        migrations.RemoveField(
            model_name='realestateagentprofile',
            name='license_info',
        ),
        migrations.RemoveField(
            model_name='realestateagentprofile',
            name='property_focus',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='taxadvisorprofile',
            name='core_services',
        ),
        migrations.RemoveField(
            model_name='taxadvisorprofile',
            name='firm_name',
        ),
        migrations.AddField(
            model_name='architectprofile',
            name='design_style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='architectprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructioncompanyprofile',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructioncompanyprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='constructioncompanyprofile',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='country',
            field=models.CharField(default='Kroatien', max_length=100),
        ),
        migrations.AddField(
            model_name='professional',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung (Original)'),
        ),
        migrations.AddField(
            model_name='professional',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='languages',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Gesprochene Sprachen'),
        ),
        migrations.AddField(
            model_name='professional',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/profiles/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_team',
            field=models.BooleanField(default=False, verbose_name='Team anzeigen'),
        ),
        migrations.AddField(
            model_name='professional',
            name='tiktok',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='twitter',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='youtube',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionalcontent',
            name='about_text',
            field=models.TextField(blank=True, null=True, verbose_name='Über uns'),
        ),
        migrations.AddField(
            model_name='professionalcontent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionalcontent',
            name='faq_text',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='professionalcontent',
            name='services_text',
            field=models.TextField(blank=True, null=True, verbose_name='Leistungen'),
        ),
        migrations.AddField(
            model_name='realestateagentprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realestateagentprofile',
            name='specialties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referenceproject',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Hervorgehoben'),
        ),
        migrations.AddField(
            model_name='taxadvisorprofile',
            name='specializations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='practice_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Firmenname'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung (Deutsch)'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='description_hr',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung (Kroatisch)'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='email_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='employee_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mitarbeiterzahl'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gründungsjahr'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verifiziert'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='must_setup_2fa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name / Firmenname'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='oib_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OIB-Nummer'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='professional_type',
            field=models.CharField(choices=[('real_estate_agent', 'Immobilienmakler'), ('construction_company', 'Bauunternehmen'), ('lawyer', 'Rechtsanwalt'), ('tax_advisor', 'Steuerberater'), ('architect', 'Architekt')], default='real_estate_agent', max_length=50),
        ),
        migrations.AlterField(
            model_name='professional',
            name='region',
            field=models.CharField(blank=True, choices=[('istrien', 'Istrien'), ('kvarner', 'Kvarner'), ('dalmatien', 'Dalmatien'), ('zagreb', 'Zagreb'), ('slavonien', 'Slavonien'), ('andere', 'Andere')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='show_contact_form',
            field=models.BooleanField(default=True, verbose_name='Kontaktformular anzeigen'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='show_listings',
            field=models.BooleanField(default=True, verbose_name='Immobilien anzeigen'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='show_references',
            field=models.BooleanField(default=True, verbose_name='Referenzen anzeigen'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='show_social_media',
            field=models.BooleanField(default=True, verbose_name='Social Media anzeigen'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='slogan',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Slogan/Motto'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='specializations',
            field=models.TextField(blank=True, null=True, verbose_name='Spezialisierungen'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professional',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='professionalcontent',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('hr', 'Hrvatski')], max_length=5),
        ),
        migrations.AlterField(
            model_name='professionalcontent',
            name='working_approach',
            field=models.TextField(blank=True, null=True, verbose_name='Arbeitsweise'),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Standort'),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='project_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Projektart'),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sortierreihenfolge'),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Projekttitel'),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='taxadvisorprofile',
            name='professional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_advisor_profile', to='main.professional'),
        ),
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('business_license', 'Gewerbeschein'), ('id_document', 'Personalausweis/Reisepass'), ('company_register', 'Handelsregisterauszug'), ('other', 'Sonstiges')], max_length=50)),
                ('file', models.FileField(upload_to='professionals/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.professional')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
            },
        ),
    ]
