# Generated by Django 4.2.1 on 2026-01-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_architectprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='Status')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Quell-URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='main.professional', verbose_name='Dienstleister')),
            ],
            options={
                'verbose_name': 'Anfrage',
                'verbose_name_plural': 'Anfragen',
                'ordering': ['-created'],
            },
        ),
    ]
