# Generated by Django 4.2.1 on 2026-01-21 16:46

from django.db import migrations, models
import django.db.models.deletion
import main.glossary_models


class Migration(migrations.Migration):

    dependencies = [
    ('main', '0012_professional_extended_fields'),
]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_key', models.SlugField(max_length=120, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Glossar-Begriff',
                'verbose_name_plural': 'Glossar-Begriffe',
                'ordering': ['canonical_key'],
            },
        ),
        migrations.CreateModel(
            name='TermCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('audience', 'Audience'), ('topic', 'Topic'), ('asset_type', 'Asset Type')], max_length=30)),
                ('key', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
                ('label_hr', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Taxonomie-Kategorie',
                'verbose_name_plural': 'Taxonomie-Kategorien',
                'ordering': ['group', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTermTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ge', 'Deutsch'), ('en', 'English'), ('hr', 'Hrvatski'), ('fr', 'Français'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('cz', 'Čeština'), ('sk', 'Slovenčina'), ('ru', 'Русский'), ('gr', 'Ελληνικά'), ('sw', 'Svenska'), ('no', 'Norsk')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('short_def', models.CharField(max_length=180, validators=[main.glossary_models.validate_short_def_120])),
                ('long_def', models.TextField(blank=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.glossaryterm')),
            ],
            options={
                'verbose_name': 'Glossar-Übersetzung',
                'verbose_name_plural': 'Glossar-Übersetzungen',
                'ordering': ['language', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTermAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ge', 'Deutsch'), ('en', 'English'), ('hr', 'Hrvatski'), ('fr', 'Français'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('cz', 'Čeština'), ('sk', 'Slovenčina'), ('ru', 'Русский'), ('gr', 'Ελληνικά'), ('sw', 'Svenska'), ('no', 'Norsk')], max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='main.glossarytermtranslation')),
            ],
            options={
                'verbose_name': 'Glossar-Alias',
                'verbose_name_plural': 'Glossar-Aliase',
            },
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='terms', to='main.termcategory'),
        ),
        migrations.AddIndex(
            model_name='glossarytermtranslation',
            index=models.Index(fields=['language', 'slug'], name='main_glossa_languag_7be344_idx'),
        ),
        migrations.AddIndex(
            model_name='glossarytermtranslation',
            index=models.Index(fields=['status'], name='main_glossa_status_7262e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='glossarytermtranslation',
            unique_together={('language', 'slug'), ('term', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='glossarytermalias',
            unique_together={('language', 'slug')},
        ),
    ]
