# Generated by Django 4.2.1 on 2026-01-21 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listing_photo_1_caption_listing_photo_2_caption_and_more'),
        ('main', '0014_glossary_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructioncompanyprofile',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='professionaldocument',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='realestateagentprofile',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='taxadvisorprofile',
            name='professional',
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='professionalcontent',
            options={'verbose_name': 'Professional Content', 'verbose_name_plural': 'Professional Contents'},
        ),
        migrations.AlterModelOptions(
            name='referenceproject',
            options={'ordering': ['-year', '-created']},
        ),
        migrations.RemoveField(
            model_name='professional',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='professionalcontent',
            name='created',
        ),
        migrations.RemoveField(
            model_name='professionalcontent',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='referenceproject',
            name='updated',
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='related_terms',
            field=models.ManyToManyField(blank=True, related_name='related_from', to='main.glossaryterm'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referenceproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/references/'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='main.professional'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('closed', 'Abgeschlossen')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Adresse *'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Stadt *'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(max_length=500, verbose_name='E-Mail *'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Firmenname *'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='oib_number',
            field=models.CharField(max_length=20, verbose_name='OIB-Nummer * (intern)'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefon *'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/profiles/', verbose_name='Profilbild'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='region',
            field=models.CharField(blank=True, choices=[('istrien', 'Istrien'), ('kvarner', 'Kvarner Bucht'), ('norddalmatien', 'Norddalmatien'), ('mitteldalmatien', 'Mitteldalmatien'), ('sueddalmatien', 'Süddalmatien'), ('zagreb', 'Stadt Zagreb'), ('zagreber_umland', 'Zagreber Umland'), ('nordkroatien', 'Nordkroatien (Varaždin & Međimurje)'), ('slawonien', 'Slawonien'), ('zentralkroatien', 'Zentralkroatien (Karlovac & Sisak)'), ('lika', 'Lika'), ('gorski_kotar', 'Gorski Kotar')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='service_regions',
            field=models.JSONField(default=list, verbose_name='Serviceregionen * (mind. 1)'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='show_contact_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='show_listings',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='show_references',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='show_social_media',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='show_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='specializations',
            field=models.JSONField(default=list, verbose_name='Spezialisierungen * (mind. 1)'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='spoken_languages',
            field=models.JSONField(default=list, verbose_name='Sprachen * (mind. 1)'),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='referenceproject',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ArchitectProfile',
        ),
        migrations.DeleteModel(
            name='ConstructionCompanyProfile',
        ),
        migrations.DeleteModel(
            name='LawyerProfile',
        ),
        migrations.DeleteModel(
            name='ProfessionalDocument',
        ),
        migrations.DeleteModel(
            name='RealEstateAgentProfile',
        ),
        migrations.DeleteModel(
            name='TaxAdvisorProfile',
        ),
    ]
