# Generated by Django 4.2.1 on 2026-01-23 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_glossary_related_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('source_path', models.CharField(help_text='Exact incoming request.path to match (case-sensitive).', max_length=512, unique=True, validators=[django.core.validators.RegexValidator(message="source_path must start with '/' and be a path only (no domain).", regex='^/.*$')])),
                ('target_url', models.CharField(help_text='Redirect destination. Use absolute URL only if required.', max_length=1024)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent (SEO default)'), (308, '308 Permanent (preserve method)'), (302, '302 Temporary'), (307, '307 Temporary (preserve method)')], default=301)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Redirect rule',
                'verbose_name_plural': 'Redirect rules',
                'indexes': [models.Index(fields=['is_active', 'source_path'], name='main_redire_is_acti_773112_idx')],
            },
        ),
    ]
