# Generated by Django 4.2.1 on 2026-01-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_agent_description_cz_agent_description_de_and_more"),
        ("main", "0001_add_professional_models"),
        ("listings", "0009_alter_listing_company_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="professional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="main.professional",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="realtor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="listings_old",
                to="accounts.agent",
            ),
        ),
    ]
