# Generated by Django 4.2.1 on 2026-01-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_add_professional_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="listing_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aktiv", "Aktiv / Online"),
                    ("pruefung", "In Prüfung"),
                    ("verkauft", "Verkauft"),
                    ("pausiert", "Pausiert"),
                ],
                default="aktiv",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="pruefung_fehler",
            field=models.TextField(
                blank=True, help_text="Fehlermeldungen bei Prüfung", null=True
            ),
        ),
    ]
