# Generated by Django 4.2.1 on 2025-01-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_alter_translation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "home"),
                    ("about", "about"),
                    ("listings", "listings"),
                    ("property details", "property details"),
                    ("blog", "blog"),
                    ("blog details", "blog details"),
                    ("contact", "contact"),
                    ("privacy", "privacy"),
                    ("navbar", "navbar"),
                    ("add-property", "add-property"),
                    ("profile", "profile"),
                    ("footer", "footer"),
                    ("login", "login"),
                    ("signup", "signup"),
                    ("faq", "faq"),
                    ("forget-password", "forget-password"),
                    ("reset-password", "reset-password"),
                ],
                max_length=50,
            ),
        ),
    ]
